eureka:
  client:
    initial-instance-info-replication-interval-seconds: 2
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
